###############################################################################
# Copyright (c) 2016, 2017 IBM Corp. and others
# 
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#      
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#    
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
# 
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
###############################################################################
language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
sudo: false
cache: ccache # https://docs.travis-ci.com/user/caching/
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libnuma-dev
      - bison
      - libdwarf-dev
      - libelf-dev
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew install ccache; fi
env:
  global:
    - GTEST_COLOR=1
    - BUILD_JOBS=2
  matrix:
    - BUILD_WITH_CMAKE=yes CMAKE_GENERATOR="Unix Makefiles"
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
  include:
    ## Auto tool builds
    #  32 bit Linux x86
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libnuma-dev
            - gcc-multilib
            - g++-multilib
      env: SPEC=linux_x86 PLATFORM=amd64-linux-gcc
    # 64 bit Linux x86
    - os: linux
      env: SPEC=linux_x86-64 PLATFORM=amd64-linux64-gcc
    # 64 bit Linux x86 compressed pointers
    - os: linux
      env: SPEC=linux_x86-64_cmprssptrs PLATFORM=amd64-linux64-gcc
    # Linter
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bison
            - clang-3.4
            - libclang-3.4-dev
            - llvm-3.4
      env: RUN_LINT=yes RUN_BUILD=no SPEC=linux_x86-64 PLATFORM=amd64-linux64-gcc
      dist: precise
    ## CMake builds
    #  Ninja builds
    #  64 bit Linux x86
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libnuma-dev
            - bison
            - libdwarf-dev
            - libelf-dev 
            - ninja-build
      env: BUILD_WITH_CMAKE=yes CMAKE_GENERATOR=Ninja
before_script:
  - ulimit -c unlimited
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/opt/ccache/libexec:$PATH ; fi
  - ccache -s -z
script:
  - bash ./scripts/build-on-travis.sh
after_script:
  - ccache -s
